// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

service on new http:Listener(9090) {
    resource function get .() returns CollectionResponsePublicImportResponse {
        return {
            results: [],
            paging: {
                next: {
                    after: "after",
                    link: "link"
                }
            }
        };
    }

    resource function get [int importId]() returns PublicImportResponse {
        return {
            state: "DONE",
            mappedObjectTypeIds: [
                "0-1"
            ],
            createdAt: "createdTime",
            updatedAt: "updatedTime",
            metadata: {
                objectLists: [],
                counters: {
                    "TOTAL_ROWS": 10,
                    "ERRORS": 3
                },
                fileIds: [
                    "184448894240"
                ]
            },
            importName: "First Contact Data",
            optOutImport: false,
            id: importId.toString()
        };
    }

    resource isolated function get [int importId]/errors() returns CollectionResponsePublicImportErrorForwardPaging {
        return {
            results: [],
            paging: {
                next: {
                    after: "after",
                    link: "link"
                }
            }
        };
    }

    resource isolated function post .() returns PublicImportResponse {
        return {
            state: "STARTED",
            importSource: "API",
            mappedObjectTypeIds: [
                "0-1"
            ],
            createdAt: "createdTime",
            updatedAt: "UpdatedTime",
            metadata: {
                objectLists: [],
                counters: {},
                fileIds: [
                    "184642347637"
                ]
            },
            importName: "First Contact Data",
            optOutImport: false,
            id: "55234002"
        };
    }

    resource isolated function post [int importId]/cancel() returns ActionResponse {
        return {
            completedAt: "completedTime",
            startedAt: "startedTime",
            status: "COMPLETE"
        };
    }
};
